### ISSUE TITLE
FQBE FQNC New Ground Layout

### ISSUE THREAD

**Issue by ghost** [VATSIM-SSA/sectorfile-fqbe#12]
FQBE Beira's FQNC requires a new ground layout as it is currently the sector's third busiest airport. 

Currently, nothing exists.

**To Do**

- [ ] KMZ Development
- [ ] KMZ Conversion to SCT Text File
- [ ] GNG Implementation of SCT Entries
- [ ] GNG Implementation of Text Labels
- [ ] GNG Implementation of Regions

**Comment by WianX05** [comment]
@miguelalbano 
[FQNC Ground Layout.zip](https://github.com/VATSIM-SSA/SSA-Ground-Layouts/files/9891003/FQNC.Ground.Layout.zip)

**Comment by RoboFun01** [comment]
Currently working on the ground radar files, it has been converted

**Comment by RoboFun01** [comment]
This is the latest KMZ that I made, currently not converted to GnG 
[FQNC_V2.zip](https://github.com/user-attachments/files/16748797/FQNC_V2.zip)

**Comment by RoboFun01** [comment]
This is a Duplicate of https://github.com/VATSIM-SSA/sectorfile-fqbe/issues/1

**Comment by RoboFun01** [comment]
@miguelalbano can you close this, as it is a duplicate of #1
